server.port=8081

spring.datasource.url=jdbc:sqlite:../knowledgehub.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL for debugging (optional)
spring.jpa.show-sql=true

# JWT Secret config
jwt.secret=knowledgehub_super_secret_key_needs_to_be_32_bytes_long!
jwt.expiration=86400000
